# VERSION v4b1
svc;sheets;names;nodes,mdiskgrp,vdisks,mdisks,hosts,cntrl,vdiskmap,rcgrp,rcmap,fcgrp,fcmap,fcports,eports

svc;cluster;toc;;Cluster;SVC Cluster Information;=COUNTIF(cluster!B:B,"L")
svc;cluster;fmt;S:15;S:3;S:15;S:18;S:23;S:14;S:14;S:14;S:30;S:11;N:13;N:10;N:10;N:10

svc;degraded;toc;degrade;Degraded Hosts;Hosts in degraded state and switch data
svc;degraded;header;SVC,Host,IOG,Host_state,WWPN,PID,state,Switch,Alias,sw_pid,sw_state,speed
svc;degraded;fmt;S:15;S:30;S:9;S:10;S:22;S:9;S:12;S:20;S25;S10

svc;nodes;toc;;Nodes;SVC Node Information
svc;nodes;cols;id,name,hardware,status,IO_group_id,IO_group_name,config_node,service_IP_address,WWNN,panel_name,code_level,enclosure_id,canister_id,enclosure_serial_number,UPS_serial_number,iscsi_name,iscsi_alias,site_id,site_name
svc;nodes;header;ID,Name,type,status,IO Group,IO Group Name,cfg node,Service IP,WWNN,panel,code,enclosuer,canister,enclouser_serial,UPS,iscsi,iscsi alias,site ID,site name
svc;nodes;fmt;  S:8;S:20;S:8; S:9;   N:9;     S:14;          S:9;     S:10;     S:18;S:9;  S:12;S:9;      S:9;     S:9;             S:11;S;   S;          S;      S

svc;license;toc;;;SVC License Information
svc;license;cols;license_virtualization,used_virtualization,license_flash,used_flash,license_remote,used_remote,license_compression_capacity,used_compression_capacity
svc;license;header;SVC,license_virtualization,used_virtualization,license_flash,used_flash,license_remote,used_remote,compression,used compression
svc;license;fmt;S:15;N:20;N:20;N:20;N:20;N:20;N:20;N:20;N:20

svc;hosts;toc;;Hosts;SVC Host Information
svc;hosts;cols;id,name,port_count,type,iogrp_count,status,vdisks,pid:state:WWPN,mask
svc;hosts;header;ID,Name,ports,host type,iogrps,status,vdisks,pid:state:WWPN,mask
svc;hosts;fmt;   S; S:15;N:8;  S:8;      N:8;   S:10;   N;    L4;S

svc;mdiskgrp;toc;pools;pools;SVC Storage Pools (mdisk groups)
svc;mdiskgrp;cols;id,name,tier,status,mdisk_count,vdisk_count,vdisks_thin,vdisks_comp,extent_size,capacity,virtual_capacity,used_capacity,real_capacity,free_capacity,pct_used,pct_free,overallocation,warning,easy_tier,easy_tier_status,capacity_raw,virtual_capacity_raw,used_capacity_raw,real_capacity_raw,free_capacity_raw,compression_uncompressed_capacity_raw,compression_compressed_capacity_raw
svc;mdiskgrp;header;ID,Pool Name,tier,status,mdisks,vdisks,thin_vols,comp_vols,ext size,total,allocated,written,consumed,free,pct used,pct free,over allocation,warning,easy tier,tier status,total_raw,allocated_raw,written_raw,consumed_raw,free_raw,uncompress_raw,compress_raw
svc;mdiskgrp;fmt;   S; S:20;     S;   S:9;   N:9;   N:9;   N:9;      N:9;      N:9;     S:9;  S:9;      S:9;    S:9;     S:9; P:9;     P:9;     N:9;            S:9;    S:9;      S;          P;        P;            P;          P;           P;       P;             P;

svc;vdisks;toc;;vdisks;SVC Virtual disk (Volume) Information
svc;vdisks;header;vdisk_name,id,copies,type,RC type,FC type,node,site,IOG,Hosts,Host Names,Pool,size,real,used,uncomp size,pct used,pct comp,RCGRP id,RCGRP Name,RC id,RC name,RC state,FC name,autoexp,copy_id,primary,se,comp,write_pri,ET,ET status,SSD,Enterprise,Nearline,warning,UID,date,total_raw,real_raw,used_raw,comp_saved,comp_raw
svc;vdisks;cols;name,id,copy_count,vdisk_type,RC_type,FC_type,preferred_node_id,site_name,IO_group_id,hosts,hostlist,mdisk_grp_name,capacity,real_capacity,used_capacity,uncompressed_used_capacity,pct_used,pct_comp,RC_GRP,RC_GRP_name,RC_id,RC_name,RC_state,FC_name,autoexpand,copy_id,primary,se_copy,compressed_copy,mirror_write_priority,easy_tier,easy_tier_status,cap_ssd,cap_enterprise,cap_nearline,warning,vdisk_UID,last_access_time,capacity_raw,real_capacity_raw,used_capacity_raw,comp_saved_raw,uncompressed_used_capacity_raw
svc;vdisks;fmt; S:20;S; N;         S;         S:8;    S:8;    N:8;              S:6;      N:6;        N:8;  S:20;    S:25;          S:9; S:9; S:9; S:10;       N;       N;       N;       S:15;   S:9;     S:9;    S:15;    S;      S:8;    N:8;    S;      S; S;   S;        S; S;        S:12;S:12;     S:12;    N;      S:25;S;  n;        n;       n;       n;         n

svc;fcgrp;toc;;FC Group;Flash Copy Consistency Groups 
svc;fcgrp;header;ID,Name,FC_ID,FC Name,Status,AutoDel,Start Time
svc;fcgrp;cols;id,name,FC_mapping_id,FC_mapping_name,status,autodelete,start_time
svc;fcgrp;fmt; S; S:20;S;            S:20;           S:14;   S;         S:13

svc;fcmap;toc;;Flash Copy;Flash Copy Mappings
svc;fcmap;header;ID,FC Map Name,source vdisk,target_vdisk,group_name,status,progress,copy rate,clean progress,incremental,partner_fc_id,partner_fc_name,restoring,start_time,rc_controller
svc;fcmap;cols;id,name,source_vdisk_name,target_vdisk_name,group_name,status,progress,copy_rate,clean_progress,incremental,partner_FC_id,partner_FC_name,restoring,start_time,rc_controlled
svc;fcmap;fmt; S;S:30;S:20;             S:20;             S:20;      S:15;  N:9;     N:9;      N:9;           S;          S;            S;              S;        S;         S

svc;rcgrp;toc;;RC Groups;SVC Remote Copy Consistency Groups
svc;rcgrp;header;RC Group,CGID,Stream,Primary_Role,Source SVC,Target SVC,RC Type,vols,state,cycle_mode,freeze
svc;rcgrp;cols;name,id,stream,primary,master_cluster_name,aux_cluster_name,copy_type,relationship_count,state,cycling_mode,freeze_time
svc;rcgrp;fmt; S:20;N; N;     S:14;   S:15;               S:15;            S:15;     N:10;              S:24; S:14;        S:20

svc;rcmap;toc;rc;RC Mappings;SVC Remote Copy (Global or Metro Mirror) Relationships
svc;rcmap;cols;id,gm_stream,consistency_group_id,consistency_group_name,name,is_source,primary,master_cluster_name,master_vdisk_name,aux_cluster_name,aux_vdisk_name,copy_type,,state,hosts,hostlist,sync,progress,id
svc;rcmap;header;ID,Stream,GRP ID,RC Group,RC Name,ST,Primary Role,Source SVC,Source vdisk,Target SVC,Target vdisk,RC Type,*,state,Hosts,Host List,sync,progress,bg_pri,cycle_mode,id
svc;rcmap;fmt;   S; S;     S;     S:20;    S:20;   S:4;S:10;       S:15;      S:22;        S:15;      S:22;        S:8;    S:4;S:22;N:7; S:20;     S:12; N:20;    S;N;S; S;       S

svc;cntrl;toc;cntrl;Controllers;Backend Storage Controller information
svc;cntrl;cols;id,controller_name,vendor_id,product_id_low,product_id_high,ctrl_s/n,degraded,max_mdisk_link_count,mdisk_link_count,allow_quorum,WWNN
svc;cntrl;header;ID,Name,vendor,product,*,serial,degrade,max links,links,quorum,WWNN
svc;cntrl;fmt;   S; S:15;S:8;   S:12;   S:6;S:14;S:9;    N:9;      N:9;  S:9;   S:18

svc;mdisks;toc;mdisks;mdisks;SVC Managed Disk Information
svc;mdisks;cols;id,name,capacity,status,mode,raid_level,mdisk_grp_name,ctrl_LUN_#,controller_name,path_count,tier,UID
svc;mdisks;header;ID,Name,Capacity,status,mode,R,Pool,LUN ,controller,paths,tier,UID
svc;mdisks;fmt;   S; S:20;S:9;     S:9;   S:9; S;S:25;S:20;S:20;      N:7;  S:10; S:66

svc;cntrlports;toc;cntrlports;Cntrl Ports;SVC Backend Storage FC Port Information
svc;cntrlports;fmt;S:15;S:15;N:8;S:18;N:8;N:8

svc;fcports;toc;fcports;fcports;SVC Fibre Channel Port Information
svc;fcports;header;Node,fc_id,port_id,WWPN,pid,state,type,use,speed,attachment
svc;fcports;cols;node_name,fc_io_port_id,port_id,WWPN,nportid,status,type,cluster_use,port_speed,attachment
svc;fcports;fmt; S:25;     N:8;          N:8;    S:18;S:9;    S:9;   S:9; S:9;        S:9;       S:10

svc;eports;toc;etherport;etherport;SVC Ethernet Port Information
svc;eports;header;Node,adapter_location,adapter_port_id,IO_group_name,state,link_state,speed,remote_copy,remote_copy_6,duplex,failover,mtu,MAC
svc;eports;cols;node_name,location,port_id,IOG,state,link_state,speed,remote_copy,remote_copy_6,duplex,failover,mtu,MAC
svc;eports;fmt; S:25;     S;       S;      S;  S:13; S:13;      S;    S;          S;            S;     S;       S;  S:16

svc;hostvol;toc;hostvol;hostvol;SVC vdisk to host mappings
svc;hostvol;fmt;S:20;S:20;S:12;S:15;N:9;N:9;N:9;S:10

svc;wwpn;toc;wwpn;wwpn;SVC Host HBA WWPN listing
svc;wwpn;fmt;S:18;S:20;S:15;S;S:12;S;S:15

svc;sevdiskcopy;toc;;sevdiskcopy;SE Virtual disk Copy
svc;sevdiskcopy;cols;vdisk_id,vdisk_name,copy_id,mdisk_grp_id,mdisk_grp_name,capacity,used_capacity,real_capacity,free_capacity,overallocation,autoexpand,warning,grainsize,se_copy,compressed_copy,uncompressed_used_capacity,parent_mdisk_grp_id,parent_mdisk_grp_name
svc;sevdiskcopy;header;Cluster,vdisk_id,vdisk_name,copy_id,mdisk_grp_id,mdisk_grp_name,capacity,used_capacity,real_capacity,free_capacity,overallocation,autoexpand,warning,grainsize,se_copy,compressed_copy,uncompressed_used_capacity,parent_mdisk_grp_id,parent_mdisk_grp_name
svc;sevdiskcopy;fmt;   S:15;   N;       S:15;      N;      N;           S:15;          S:10;    S:10;         S:10;         S:10;         N;             S;         N;      S:9;      N;      S;              S:10;                      N;                  S:10;

svc;iog;toc;iog;;IOG
svc;iog;cols;name,node_count,vdisk_count,host_count,flash_copy_total_memory,flash_copy_free_memory,remote_copy_total_memory,remote_copy_free_memory,mirroring_total_memory,mirroring_free_memory,raid_total_memory,raid_free_memory,maintenance,compression_active,accessible_vdisk_count,compression_supported,max_enclosures,encryption_supported
svc;iog;header;SVC ,name,node_count,vdisk_count,host_count,flash_copy_total_memory,flash_copy_free_memory,remote_copy_total_memory,remote_copy_free_memory,mirroring_total_memory,mirroring_free_memory,raid_total_memory,raid_free_memory,maintenance,compression_active,accessible_vdisk_count,compression_supported,max_enclosures,encryption_supported
svc;iog;fmt;   S:15;S:20

svc;eventlog;toc;;eventlog;Event Log
svc;eventlog;cols;sequence_number,last_timestamp,object_type,object_id,object_name,copy_id,status,fixed,event_id,error_code,description
svc;eventlog;header;Cluster,sequence_number,last_timestamp,object_type,object_id,object_name,copy_id,status,fixed,event_id,error_code,description
svc;eventlog;fmt;   S:20;   N;              S:20;          S:15;       S;        S:20;       S;      S;     S;    N;       S:12;      S:20

svc;vdiskmap;toc;;vdiskmap;vdisk to host mappings
svc;vdiskmap;cols;host_id,name,vdisk_name,SCSI_id,IO_group_id,vdisk_UID
svc;vdiskmap;header;ID,Host,vdisk,scsi,iog,UID
svc;vdiskmap;fmt;S;S:20;S:30;S;N;S:40

v7k;cluster2;toc;cluster;Cluster;Storwize Cluster Information
v7k;cluster2;fmt;S:15;S:3;S:15;S:18;S:23;S:14;S:14;S:14;S:30;S:11;N:13;N:10;N:10;N:10

v7k;enclosures;toc;enclosures;Enclosures;Enclosures listing
v7k;enclosures;cols;id,status,type,managed,IO_group_id,IO_group_name,product_MTM,serial_number,total_canisters,online_canisters,total_PSUs,online_PSUs,drive_slots,total_fan_modules,online_fan_modules
v7k;enclosures;header;Mach,id,status,type,managed,IO_group_id,IO_group_name,product_MTM,serial_number,total_canisters,online_canisters,total_PSUs,online_PSUs,drive_slots,total_fan_modules,online_fan_modules
v7k;enclosures;fmt;   S:20;N;S;     S:10;S;      N;          S:10;         S:10;       S:10;N;N;N;N;N;N;N

v7k;drives;toc;drives;Drives;Drives listing
v7k;drives;cols;id,status,error_sequence_number,use,tech_type,capacity,mdisk_id,mdisk_name,member_id,enclosure_id,slot_id,node_id,node_name
v7k;drives;header;Mach,id,status,error_sequence_number,use,tech_type,capacity,mdisk_id,mdisk_name,member_id,enclosure_id,slot_id,node_id,node_name
v7k;drives;fmt;   S:20;N; S:9;   S:9;                  S:9;S:12;     S:9;     N;       S:15;      N;        N;N;S:10;S:20